@startuml

!include ./format.iuml

actor Patient as u
box Other Loyal Services
participant Outreach as o
participant HRA as hra
participant Hermes as msg
end box
participant ConditionalForms as cf $loyalRed

!$showNote = 1
!$showError = 1

!procedure sideNote($msg)
!if ($showNote == 1)
note right : $msg
!endprocedure


== Start Form ==
loop Patient Campaign
    o ->> hra: Get URL
    hra ->> o: URL
    hra ->> msg: Send Missive
    sideNote("Generate message\nfor code")
    msg -->> u: Missive
end

u ->> hra: Start Form
hra ->> hra: Generate code
hra ->> msg: Send user code
msg -->> u: Code

u ->> hra: Enter code
!if ($showError)
alt #Red
hra ->> u : Bad code
end alt
!endif
hra ->> u: Cookie/JWT
u ->> hra: Start Form with cookie
loop Run form
    u ->> hra: Next Step
    hra ->> cf: Next Step
    cf ->> cf: Work
    cf ->> hra: Step
    hra ->> u: Step
end

== Resume Form ==

u ->> hra: Next Step no valid cookie/jwt
hra ->> hra: Generate code
hra ->> msg: Send user code
msg -->> u: Code

u ->> hra: Enter code
hra ->> u: Cookie/JWT
loop Run form
    u ->> hra: Next Step
    hra ->> cf: Next Step
    cf ->> cf: Work
    cf ->> hra: Step
    hra ->> u: Step
end

@enduml